[package]
name="zuva_benchmarks"
version.workspace=true
edition.workspace=true
publish=false

[dependencies]
zuva_frontend={path="../crates/zuva_frontend"}
zuva_vm={path="../crates/zuva_vm"}
criterion.workspace=true

[[bench]]
name="lexer"
harness=false

[[bench]]
name="parser"
harness=false

[[bench]]
name="vm"
harness=false
